serverAddr = "{{ .Envs.FRP_SERVER }}"
serverPort = {{ .Envs.FRP_PORT }}
auth.method = "token"
auth.token = "{{ .Envs.FRP_TOKEN }}"
loginFailExit = false

[[proxies]]
name = "genesis-evidence"
type = "http"
localIP = "127.0.0.1"
localPort = 8127
subdomain = "genesis-evidence"

[[proxies]]
name = "genesis-evidence-review"
type = "http"
localIP = "127.0.0.1"
localPort = 8126
subdomain = "genesis-evidence-review"
